export const TEST_STUDENTS = [
    {
        smail: "cs24b001@smail.iitm.ac.in",
        fullName: "Rahul Kumar Parvam",
        displayName: "Rahul K",
        username: "rahul_k",
    },
    {
        smail: "cs24b002@smail.iitm.ac.in",
        fullName: "Rahul Kumar Singh",
        displayName: "Rahul S",
        username: "rahul_singh",
    },
    {
        smail: "cs24b003@smail.iitm.ac.in",
        fullName: "Karan Malhotra",
        displayName: "Karan M",
        username: "karan_mal",
    },
    {
        smail: "cs24b004@smail.iitm.ac.in",
        fullName: "Priya Sharma",
        displayName: "Priya",
        username: "priya_s",
    },
    {
        smail: "cs24b005@smail.iitm.ac.in",
        fullName: "Amit Kumar Reddy",
        displayName: "Amit",
        username: "amit_kr",
    },
    {
        smail: "cs24b006@smail.iitm.ac.in",
        fullName: "Shreya Gupta",
        displayName: "Shreya",
        username: "shreya_g",
    },
    {
        smail: "cs24b007@smail.iitm.ac.in",
        fullName: "Vikram Patel",
        displayName: "Vikram",
        username: "vikram_p",
    },
    {
        smail: "cs24b008@smail.iitm.ac.in",
        fullName: "Neha Joshi",
        displayName: "Neha",
        username: "neha_j",
    },
    {
        smail: "cs24b009@smail.iitm.ac.in",
        fullName: "Arjun Verma",
        displayName: "Arjun",
        username: "arjun_v",
    },
    {
        smail: "cs24b010@smail.iitm.ac.in",
        fullName: "Divya Singh",
        displayName: "Divya",
        username: "divya_s",
    },
    {
        smail: "cs24b011@smail.iitm.ac.in",
        fullName: "Kabir Hassan Khan",
        displayName: "Kabir",
        username: "kabir_hk",
    },
    {
        smail: "cs24b012@smail.iitm.ac.in",
        fullName: "Siddharth Mehta",
        displayName: "Sid",
        username: "sid_mehta",
    },
    {
        smail: "cs24b013@smail.iitm.ac.in",
        fullName: "Ananya Bhat",
        displayName: "Ananya",
        username: "ananya_b",
    },
    {
        smail: "cs24b014@smail.iitm.ac.in",
        fullName: "Rohit Kumar",
        displayName: "Rohit",
        username: "rohit_k",
    },
    {
        smail: "cs24b015@smail.iitm.ac.in",
        fullName: "Pooja Verma",
        displayName: "Pooja",
        username: "pooja_v",
    },
    {
        smail: "cs24b016@smail.iitm.ac.in",
        fullName: "Harsh Agarwal",
        displayName: "Harsh",
        username: "harsh_a",
    },
    {
        smail: "cs24b017@smail.iitm.ac.in",
        fullName: "Sneha Rao",
        displayName: "Sneha",
        username: "sneha_r",
    },
    {
        smail: "cs24b018@smail.iitm.ac.in",
        fullName: "Kunal Sharma Kumar",
        displayName: "Kunal",
        username: "kunal_sk",
    },
    {
        smail: "cs24b019@smail.iitm.ac.in",
        fullName: "Mira Sinha",
        displayName: "Mira",
        username: "mira_s",
    },
    {
        smail: "cs24b020@smail.iitm.ac.in",
        fullName: "Aditya Malhotra",
        displayName: "Aditya",
        username: "aditya_m",
    },
];
