export const ORGANIZATION_DUTY_CODE = {
    ORG_PROFILE_UPDATE: "org.profile.update",
    ORG_MEDIA_UPDATE: "org.media.update",
    ORG_POST_CREATE: "org.post.create",
    ORG_POST_UPDATE: "org.post.update",
    ORG_POST_DELETE: "org.post.delete",
    ORG_COMMENT_MODERATE: "org.comment.moderate",
    ORG_MEMBER_ADD: "org.member.add",
    ORG_MEMBER_APPROVE: "org.member.approve",
    ORG_MEMBER_REMOVE: "org.member.remove",
    ORG_TENURE_CREATE: "org.tenure.create",
    ORG_TENURE_UPDATE: "org.tenure.update",
    ORG_ROLE_CONFIG_UPDATE: "org.role_config.update",
    ORG_DUTY_POLICY_UPDATE: "org.duty_policy.update",
} as const;

export type OrganizationDutyCode =
    (typeof ORGANIZATION_DUTY_CODE)[keyof typeof ORGANIZATION_DUTY_CODE];

export const ORGANIZATION_DUTY_CODE_ENUM = [
    ORGANIZATION_DUTY_CODE.ORG_PROFILE_UPDATE,
    ORGANIZATION_DUTY_CODE.ORG_MEDIA_UPDATE,
    ORGANIZATION_DUTY_CODE.ORG_POST_CREATE,
    ORGANIZATION_DUTY_CODE.ORG_POST_UPDATE,
    ORGANIZATION_DUTY_CODE.ORG_POST_DELETE,
    ORGANIZATION_DUTY_CODE.ORG_COMMENT_MODERATE,
    ORGANIZATION_DUTY_CODE.ORG_MEMBER_ADD,
    ORGANIZATION_DUTY_CODE.ORG_MEMBER_APPROVE,
    ORGANIZATION_DUTY_CODE.ORG_MEMBER_REMOVE,
    ORGANIZATION_DUTY_CODE.ORG_TENURE_CREATE,
    ORGANIZATION_DUTY_CODE.ORG_TENURE_UPDATE,
    ORGANIZATION_DUTY_CODE.ORG_ROLE_CONFIG_UPDATE,
    ORGANIZATION_DUTY_CODE.ORG_DUTY_POLICY_UPDATE,
] as const;
