import { ORGANIZATION_CATEGORY } from "../../organizations/constants/organization.constants";

export const POR_SCOPE = {
    INSTITUTE: "institute",
    HOSTEL: "hostel",
    ORGANIZATION: "organization",
    SUPPORT: "support",
} as const;

export type PORScope = (typeof POR_SCOPE)[keyof typeof POR_SCOPE];

export interface PORSeedRoleDefinition {
    roleKey: string;
    displayName: string;
    scope: PORScope;
    appliesToCategories: readonly (typeof ORGANIZATION_CATEGORY)[keyof typeof ORGANIZATION_CATEGORY][];
    defaultSortOrder?: number;
    isSystem?: boolean;
    aliases?: string[];
    description?: string;
}

export const POR_SEED_ROLE_GROUPS = {
    INSTITUTE: [
        {
            roleKey: "sgs",
            displayName: "Student General Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 1,
            isSystem: true,
            aliases: [
                "sgs",
                "student general secretary",
                "student government head",
            ],
            description: "Head of institute student governance",
        },
        {
            roleKey: "aas",
            displayName: "Academic Affairs Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 2,
            isSystem: true,
            aliases: ["aas", "academic secretary", "academic affairs sec"],
            description:
                "Handles academic affairs and student academic representation",
        },
        {
            roleKey: "cocas",
            displayName: "Co-Curricular Affairs Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 3,
            isSystem: true,
            aliases: [
                "cocas",
                "co-curricular secretary",
                "co curricular affairs sec",
            ],
            description: "Handles co-curricular activity coordination",
        },
        {
            roleKey: "has",
            displayName: "Hostel Affairs Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 4,
            isSystem: true,
            aliases: ["has", "hostel secretary", "hostel affairs sec"],
            description: "Handles hostel-level governance at institute level",
        },
        {
            roleKey: "cultural_affairs_secretary",
            displayName: "Cultural Affairs Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 5,
            isSystem: true,
            aliases: [
                "arts secretary",
                "literary secretary",
                "cultural secretary",
            ],
            description: "Handles institute cultural coordination",
        },
        {
            roleKey: "iss",
            displayName: "Institute Sports Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 6,
            isSystem: true,
            aliases: ["iss", "sports secretary", "institute sports sec"],
            description: "Handles institute sports affairs",
        },
        {
            roleKey: "ras",
            displayName: "Research Affairs Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 7,
            isSystem: true,
            aliases: ["ras", "research secretary", "research affairs sec"],
            description:
                "Handles student research representation and initiatives",
        },
        {
            roleKey: "iar",
            displayName: "International & Alumni Relations Secretary",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 8,
            isSystem: true,
            aliases: [
                "iar",
                "international secretary",
                "alumni relations secretary",
            ],
            description: "Handles international and alumni relations",
        },
        {
            roleKey: "speaker",
            displayName: "Speaker",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 9,
            isSystem: true,
            aliases: ["slc speaker", "speaker of slc"],
            description: "Presiding officer of the student legislative council",
        },
        {
            roleKey: "dept_legislator",
            displayName: "Department Legislator",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.DEPARTMENT],
            defaultSortOrder: 10,
            isSystem: true,
            aliases: ["department legislator", "dept legislator", "dl"],
            description: "Represents a department in student governance",
        },
        {
            roleKey: "hostel_legislator",
            displayName: "Hostel Legislator",
            scope: POR_SCOPE.INSTITUTE,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 11,
            isSystem: true,
            aliases: ["hostel legislator", "hl", "hostel rep"],
            description: "Represents a hostel in student governance",
        },
    ] satisfies PORSeedRoleDefinition[],
    HOSTEL: [
        {
            roleKey: "hgensec",
            displayName: "Hostel General Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 1,
            isSystem: true,
            aliases: ["hgensec", "hostel gensec", "hostel general secretary"],
            description: "Head of a hostel council",
        },
        {
            roleKey: "social_secretary",
            displayName: "Social Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 2,
            isSystem: true,
            aliases: ["social sec", "social secretary", "social"],
            description: "Handles hostel social and community events",
        },
        {
            roleKey: "health_hygiene_secretary",
            displayName: "Health and Hygiene Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 3,
            isSystem: true,
            aliases: ["hh secretary", "health secretary", "hygiene secretary"],
            description: "Oversees hostel health, hygiene, and sanitation",
        },
        {
            roleKey: "technical_affairs_secretary",
            displayName: "Technical Affairs Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 4,
            isSystem: true,
            aliases: [
                "technical secretary",
                "tech sec",
                "technical affairs sec",
            ],
            description: "Handles hostel technical facilities and initiatives",
        },
        {
            roleKey: "hostel_sports_secretary",
            displayName: "Hostel Sports Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 5,
            isSystem: true,
            aliases: ["sports secretary", "hostel sports sec"],
            description: "Handles hostel sports activities",
        },
        {
            roleKey: "hostel_cultural_secretary",
            displayName: "Hostel Cultural Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 6,
            isSystem: true,
            aliases: ["cultural secretary", "hostel cultural sec"],
            description: "Handles hostel cultural activities",
        },
        {
            roleKey: "hostel_literary_secretary",
            displayName: "Hostel Literary Secretary",
            scope: POR_SCOPE.HOSTEL,
            appliesToCategories: [ORGANIZATION_CATEGORY.HOSTEL],
            defaultSortOrder: 7,
            isSystem: true,
            aliases: ["literary secretary", "hostel literary sec"],
            description: "Handles hostel literary activities",
        },
    ] satisfies PORSeedRoleDefinition[],
    ORGANIZATION: [
        {
            roleKey: "core",
            displayName: "Core",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
                ORGANIZATION_CATEGORY.INSTITUTE_BODY,
            ],
            defaultSortOrder: 1,
            isSystem: true,
            aliases: ["core", "student head", "core member"],
            description:
                "Top-tier execution and leadership role in an organization",
        },
        {
            roleKey: "head",
            displayName: "Head",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
            ],
            defaultSortOrder: 2,
            isSystem: true,
            aliases: ["head", "team head", "project head"],
            description:
                "Leads a specific team or vertical within an organization",
        },
        {
            roleKey: "coordinator",
            displayName: "Coordinator",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
            ],
            defaultSortOrder: 3,
            isSystem: true,
            aliases: ["coord", "coordinator", "team coordinator"],
            description: "Coordinates execution across a function or vertical",
        },
        {
            roleKey: "deputy_coordinator",
            displayName: "Deputy Coordinator",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
            ],
            defaultSortOrder: 4,
            isSystem: true,
            aliases: ["dep coord", "dcoord", "deputy coord"],
            description: "Assists the coordinator in execution and operations",
        },
        {
            roleKey: "lead",
            displayName: "Lead",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
            ],
            defaultSortOrder: 5,
            isSystem: true,
            aliases: ["team lead", "lead"],
            description: "Common role for technical or functional team leads",
        },
        {
            roleKey: "manager",
            displayName: "Manager",
            scope: POR_SCOPE.ORGANIZATION,
            appliesToCategories: [
                ORGANIZATION_CATEGORY.CLUB,
                ORGANIZATION_CATEGORY.TEAM,
                ORGANIZATION_CATEGORY.FEST,
                ORGANIZATION_CATEGORY.COMMITTEE,
            ],
            defaultSortOrder: 6,
            isSystem: true,
            aliases: ["strategist", "manager", "ops manager"],
            description: "Used for operational or planning-heavy roles",
        },
    ] satisfies PORSeedRoleDefinition[],
    SUPPORT: [
        {
            roleKey: "student_mentor",
            displayName: "Student Mentor",
            scope: POR_SCOPE.SUPPORT,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 1,
            isSystem: true,
            aliases: ["mentor", "gcu mentor", "student mentor"],
            description: "Provides mentoring and student support",
        },
        {
            roleKey: "mitr_student_advisor",
            displayName: "Mitr Student Advisor",
            scope: POR_SCOPE.SUPPORT,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 2,
            isSystem: true,
            aliases: ["mitr advisor", "student advisor", "mitr"],
            description: "Student advisor role for wellness support",
        },
        {
            roleKey: "executive_editor",
            displayName: "Executive Editor",
            scope: POR_SCOPE.SUPPORT,
            appliesToCategories: [ORGANIZATION_CATEGORY.INSTITUTE_BODY],
            defaultSortOrder: 3,
            isSystem: true,
            aliases: ["exec editor", "editor", "executive editor"],
            description: "Editorial leadership role for student media",
        },
    ] satisfies PORSeedRoleDefinition[],
} as const;

export const POR_SEED_ROLES = [
    ...POR_SEED_ROLE_GROUPS.INSTITUTE,
    ...POR_SEED_ROLE_GROUPS.HOSTEL,
    ...POR_SEED_ROLE_GROUPS.ORGANIZATION,
    ...POR_SEED_ROLE_GROUPS.SUPPORT,
] satisfies readonly PORSeedRoleDefinition[];
